# Pandas

In [1]:
import numpy as np
import pandas as pd

### Series 
series out of  a list

In [3]:
x = pd.Series([10,20,30,40,50])
x

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
x.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
x.values

array([10, 20, 30, 40, 50], dtype=int64)

In [6]:
x.dtype

dtype('int64')

#### Data with our own labels

In [9]:
data = [450,650,870]
sales = pd.Series(data, index=['Bob','Sally','Tom'])
sales

Bob      450
Sally    650
Tom      870
dtype: int64

In [10]:
sales.index

Index(['Bob', 'Sally', 'Tom'], dtype='object')

In [11]:
sales["Bob"]

450

In [13]:
#same as
sales[0]
#only if the data labels are not numerical ie won't get confused with indexing

450

In [14]:
#use bools to filter out data

In [15]:
sales > 500

Bob      False
Sally     True
Tom       True
dtype: bool

In [16]:
sales[sales > 500]

Sally    650
Tom      870
dtype: int64

In [17]:
#check if data present with index
'Bob' in sales

True

In [18]:
650 in sales #checks the index not to value

False

In [19]:
sales_dict = sales.to_dict()
sales_dict

{'Bob': 450, 'Sally': 650, 'Tom': 870}

In [20]:
sales_ser = pd.Series(sales_dict)
sales_ser

Bob      450
Sally    650
Tom      870
dtype: int64

In [21]:
new_sales = pd.Series(sales, index=['Sally', 'Lucy', 'Bob', 'Tom', 'Darren'])
new_sales
#change order of series but also add new indexes that are auto assignes NaN

Sally     650.0
Lucy        NaN
Bob       450.0
Tom       870.0
Darren      NaN
dtype: float64

In [22]:
#check if values are Nan with numpy
np.isnan(new_sales)

Sally     False
Lucy       True
Bob       False
Tom       False
Darren     True
dtype: bool

In [24]:
#same with pandas
pd.isnull(new_sales)

Sally     False
Lucy       True
Bob       False
Tom       False
Darren     True
dtype: bool

In [26]:
new_sales.index.name = "Sales_Person" #naming indexes
new_sales

Sales_Person
Sally     650.0
Lucy        NaN
Bob       450.0
Tom       870.0
Darren      NaN
dtype: float64

In [27]:
#naming whole series
new_sales.name = "total sales"
new_sales

Sales_Person
Sally     650.0
Lucy        NaN
Bob       450.0
Tom       870.0
Darren      NaN
Name: total sales, dtype: float64

# DataFrames

In [29]:
data = [['Don',870],["Sally",678],['Bob',4756]]
df = pd.DataFrame(data, columns=["Name","Sales"])
df #makes autoincrementing index if one not actually specified

    Name  Sales
0    Don    870
1  Sally    678
2    Bob   4756

In [30]:
df_dict = pd.DataFrame(sales_dict)
df_dict

ValueError: If using all scalar values, you must pass an index

In [31]:
df_dict = pd.DataFrame(sales_dict, index=[1,2,3])
df_dict

   Bob  Sally  Tom
1  450    650  870
2  450    650  870
3  450    650  870

In [32]:
sales_dict

{'Bob': 450, 'Sally': 650, 'Tom': 870}

In [34]:
df_dict = pd.DataFrame(sales_dict, index=["Sales"])
df_dict

       Bob  Sally  Tom
Sales  450    650  870

### Create datafram from list of dictionaries

In [35]:
dict_list = [{'Name':'Tom','Sales':250},{'Name':'Jane','Sales':300},{'Name':'Steve','Sales':350}
            ,{'Name':'Lucy','Sales':400}]

df_dict_list = pd.DataFrame(dict_list)
df_dict_list  #Now it know how we want it formatted because there are keys for column names

    Name  Sales
0    Tom    250
1   Jane    300
2  Steve    350
3   Lucy    400

## Create datafram out of series

In [36]:
east = pd.Series([1000,1200,3400],index=['Q1','Q2','Q3'])
west = pd.Series([1100,1300,2400,3500],index=['Q1','Q2','Q3','Q4'])

In [37]:
df_region = pd.DataFrame({'East':east, 'West':west})
df_region

      East  West
Q1  1000.0  1100
Q2  1200.0  1300
Q3  3400.0  2400
Q4     NaN  3500

In [38]:
years = ["2015","2016","2017","2018"]
df_region["Years"] = years
df_region
# adds it on but doesn't make sense for this example. just to see how to add columns

      East  West Years
Q1  1000.0  1100  2015
Q2  1200.0  1300  2016
Q3  3400.0  2400  2017
Q4     NaN  3500  2018

In [39]:
df_region = df_region.set_index("Years")  # wrong about quarters, want years instead
df_region

         East  West
Years
2015   1000.0  1100
2016   1200.0  1300
2017   3400.0  2400
2018      NaN  3500

In [40]:
#reindex shifts index
new_df = df_region.reindex(["2014","2015","2016","2017","2018","2019","2020"])
new_df

         East    West
Years
2014      NaN     NaN
2015   1000.0  1100.0
2016   1200.0  1300.0
2017   3400.0  2400.0
2018      NaN  3500.0
2019      NaN     NaN
2020      NaN     NaN

In [42]:
#can also use reindex on columns maybe for reorganising
new_df = new_df.reindex(columns=["East","South","West"])
new_df

         East  South    West
Years
2014      NaN    NaN     NaN
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0
2017   3400.0    NaN  2400.0
2018      NaN    NaN  3500.0
2019      NaN    NaN     NaN
2020      NaN    NaN     NaN

## How to deal with missing values.

In [44]:
#replace NaN's with zeros
new_df.fillna(0)

         East  South    West
Years
2014      0.0    0.0     0.0
2015   1000.0    0.0  1100.0
2016   1200.0    0.0  1300.0
2017   3400.0    0.0  2400.0
2018      0.0    0.0  3500.0
2019      0.0    0.0     0.0
2020      0.0    0.0     0.0

In [47]:
new_df.fillna(method='ffill')

         East  South    West
Years
2014      NaN    NaN     NaN
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0
2017   3400.0    NaN  2400.0
2018   3400.0    NaN  3500.0
2019   3400.0    NaN  3500.0
2020   3400.0    NaN  3500.0

In [48]:
new_df.fillna(method='bfill')

         East  South    West
Years
2014   1000.0    NaN  1100.0
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0
2017   3400.0    NaN  2400.0
2018      NaN    NaN  3500.0
2019      NaN    NaN     NaN
2020      NaN    NaN     NaN

In [49]:
new_df.interpolate() #default method linear interpolation kinda like making a line of best fit???

         East  South    West
Years
2014      NaN    NaN     NaN
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0
2017   3400.0    NaN  2400.0
2018   3400.0    NaN  3500.0
2019   3400.0    NaN  3500.0
2020   3400.0    NaN  3500.0

In [51]:
new_df.dropna(axis=1, how='all')  #axis 1 refers to cols, axis 0 refers to row

         East    West
Years
2014      NaN     NaN
2015   1000.0  1100.0
2016   1200.0  1300.0
2017   3400.0  2400.0
2018      NaN  3500.0
2019      NaN     NaN
2020      NaN     NaN

In [52]:
new_df.dropna(axis=0, how='all') #if all values in row in nan then drop

         East  South    West
Years
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0
2017   3400.0    NaN  2400.0
2018      NaN    NaN  3500.0

In [54]:
new_df.dropna(thresh=2) #dnt drop if more

         East  South    West
Years
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0
2017   3400.0    NaN  2400.0

In [55]:
new_df.drop("2019")

         East  South    West
Years
2014      NaN    NaN     NaN
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0
2017   3400.0    NaN  2400.0
2018      NaN    NaN  3500.0
2020      NaN    NaN     NaN

In [57]:
new_df.drop("South", axis = 1)

         East    West
Years
2014      NaN     NaN
2015   1000.0  1100.0
2016   1200.0  1300.0
2017   3400.0  2400.0
2018      NaN  3500.0
2019      NaN     NaN
2020      NaN     NaN

In [58]:
new_df["East"]

Years
2014       NaN
2015    1000.0
2016    1200.0
2017    3400.0
2018       NaN
2019       NaN
2020       NaN
Name: East, dtype: float64

In [60]:
new_df.iloc[2]

East     1200.0
South       NaN
West     1300.0
Name: 2016, dtype: float64

In [61]:
new_df.iloc[1:3]

         East  South    West
Years
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0

In [62]:
new_df.loc[["2016","2019"]]

         East  South    West
Years
2016   1200.0    NaN  1300.0
2019      NaN    NaN     NaN

In [63]:
new_df

         East  South    West
Years
2014      NaN    NaN     NaN
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0
2017   3400.0    NaN  2400.0
2018      NaN    NaN  3500.0
2019      NaN    NaN     NaN
2020      NaN    NaN     NaN

In [64]:
new_df.sort_index(ascending=False)

         East  South    West
Years
2020      NaN    NaN     NaN
2019      NaN    NaN     NaN
2018      NaN    NaN  3500.0
2017   3400.0    NaN  2400.0
2016   1200.0    NaN  1300.0
2015   1000.0    NaN  1100.0
2014      NaN    NaN     NaN

In [65]:
new_df.sort_index(ascending=0)

         East  South    West
Years
2020      NaN    NaN     NaN
2019      NaN    NaN     NaN
2018      NaN    NaN  3500.0
2017   3400.0    NaN  2400.0
2016   1200.0    NaN  1300.0
2015   1000.0    NaN  1100.0
2014      NaN    NaN     NaN

In [66]:
new_df.sort_values(by=["East"])

         East  South    West
Years
2015   1000.0    NaN  1100.0
2016   1200.0    NaN  1300.0
2017   3400.0    NaN  2400.0
2014      NaN    NaN     NaN
2018      NaN    NaN  3500.0
2019      NaN    NaN     NaN
2020      NaN    NaN     NaN

In [70]:
iris = pd.read_csv("iris.csv")
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [87]:
group_by_species = iris.groupby(by="species", axis=0)
[print(i) for i in group_by_species]
group_by_species

('setosa',     sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa)
('versicolor',     sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor)
('virginica',      sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
106           4.9          2.5           4.5          1.7  virginica
107           7.3          2.9           6.3          1.8  virginica
108           6.7          2.5           5.8          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
110           6.5          3.2           5.1          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
112           6.8          3.0           5.5          2.1  virginica
113           5.7          2.5           5.0          2.0  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
116           6.5          3.0           5.5          1.8  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica)

In [83]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [84]:
group_by_species.describe()

           sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_length      petal_width         \
                 count   mean  ...          75%  max       count   mean
species                        ...
setosa            50.0  3.418  ...        1.575  1.9        50.0  0.244
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
species
setosa      0.107210  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [88]:
group_by_species = iris.groupby(by=["species","sepal_length"], axis=0)
[print(i) for i in group_by_species]

(('setosa', 4.3),     sepal_length  sepal_width  petal_length  petal_width species
13           4.3          3.0           1.1          0.1  setosa)
(('setosa', 4.4),     sepal_length  sepal_width  petal_length  petal_width species
8            4.4          2.9           1.4          0.2  setosa
38           4.4          3.0           1.3          0.2  setosa
42           4.4          3.2           1.3          0.2  setosa)
(('setosa', 4.5),     sepal_length  sepal_width  petal_length  petal_width species
41           4.5          2.3           1.3          0.3  setosa)
(('setosa', 4.6),     sepal_length  sepal_width  petal_length  petal_width species
3            4.6          3.1           1.5          0.2  setosa
6            4.6          3.4           1.4          0.3  setosa
22           4.6          3.6           1.0          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa)
(('setosa', 4.7),     sepal_length  sepal_width  petal_length  petal_width species
2            4.7          3.2           1.3          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa)
(('setosa', 4.8),     sepal_length  sepal_width  petal_length  petal_width species
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
24           4.8          3.4           1.9          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
45           4.8          3.0           1.4          0.3  setosa)
(('setosa', 4.9),     sepal_length  sepal_width  petal_length  petal_width species
1            4.9          3.0           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
34           4.9          3.1           1.5          0.1  setosa
37           4.9          3.1           1.5          0.1  setosa)
(('setosa', 5.0),     sepal_length  sepal_width  petal_length  petal_width species
4            5.0          3.6           1.4          0.2  setosa
7            5.0          3.4           1.5          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
35           5.0          3.2           1.2          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
43           5.0          3.5           1.6          0.6  setosa
49           5.0          3.3           1.4          0.2  setosa)
(('setosa', 5.1),     sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
17           5.1          3.5           1.4          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
21           5.1          3.7           1.5          0.4  setosa
23           5.1          3.3           1.7          0.5  setosa
39           5.1          3.4           1.5          0.2  setosa
44           5.1          3.8           1.9          0.4  setosa
46           5.1          3.8           1.6          0.2  setosa)
(('setosa', 5.2),     sepal_length  sepal_width  petal_length  petal_width species
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
32           5.2          4.1           1.5          0.1  setosa)
(('setosa', 5.3),     sepal_length  sepal_width  petal_length  petal_width species
48           5.3          3.7           1.5          0.2  setosa)
(('setosa', 5.4),     sepal_length  sepal_width  petal_length  petal_width species
5            5.4          3.9           1.7          0.4  setosa
10           5.4          3.7           1.5          0.2  setosa
16           5.4          3.9           1.3          0.4  setosa
20           5.4          3.4           1.7          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa)
(('setosa', 5.5),     sepal_length  sepal_width  petal_length  petal_width species
33           5.5          4.2           1.4          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa)
(('setosa', 5.7),     sepal_length  sepal_width  petal_length  petal_width species
15           5.7          4.4           1.5          0.4  setosa
18           5.7          3.8           1.7          0.3  setosa)
(('setosa', 5.8),     sepal_length  sepal_width  petal_length  petal_width species
14           5.8          4.0           1.2          0.2  setosa)
(('versicolor', 4.9),     sepal_length  sepal_width  petal_length  petal_width     species
57           4.9          2.4           3.3          1.0  versicolor)
(('versicolor', 5.0),     sepal_length  sepal_width  petal_length  petal_width     species
60           5.0          2.0           3.5          1.0  versicolor
93           5.0          2.3           3.3          1.0  versicolor)
(('versicolor', 5.1),     sepal_length  sepal_width  petal_length  petal_width     species
98           5.1          2.5           3.0          1.1  versicolor)
(('versicolor', 5.2),     sepal_length  sepal_width  petal_length  petal_width     species
59           5.2          2.7           3.9          1.4  versicolor)
(('versicolor', 5.4),     sepal_length  sepal_width  petal_length  petal_width     species
84           5.4          3.0           4.5          1.5  versicolor)
(('versicolor', 5.5),     sepal_length  sepal_width  petal_length  petal_width     species
53           5.5          2.3           4.0          1.3  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor)
(('versicolor', 5.6),     sepal_length  sepal_width  petal_length  petal_width     species
64           5.6          2.9           3.6          1.3  versicolor
66           5.6          3.0           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
88           5.6          3.0           4.1          1.3  versicolor
94           5.6          2.7           4.2          1.3  versicolor)
(('versicolor', 5.7),     sepal_length  sepal_width  petal_length  petal_width     species
55           5.7          2.8           4.5          1.3  versicolor
79           5.7          2.6           3.5          1.0  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
99           5.7          2.8           4.1          1.3  versicolor)
(('versicolor', 5.8),     sepal_length  sepal_width  petal_length  petal_width     species
67           5.8          2.7           4.1          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
92           5.8          2.6           4.0          1.2  versicolor)
(('versicolor', 5.9),     sepal_length  sepal_width  petal_length  petal_width     species
61           5.9          3.0           4.2          1.5  versicolor
70           5.9          3.2           4.8          1.8  versicolor)
(('versicolor', 6.0),     sepal_length  sepal_width  petal_length  petal_width     species
62           6.0          2.2           4.0          1.0  versicolor
78           6.0          2.9           4.5          1.5  versicolor
83           6.0          2.7           5.1          1.6  versicolor
85           6.0          3.4           4.5          1.6  versicolor)
(('versicolor', 6.1),     sepal_length  sepal_width  petal_length  petal_width     species
63           6.1          2.9           4.7          1.4  versicolor
71           6.1          2.8           4.0          1.3  versicolor
73           6.1          2.8           4.7          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor)
(('versicolor', 6.2),     sepal_length  sepal_width  petal_length  petal_width     species
68           6.2          2.2           4.5          1.5  versicolor
97           6.2          2.9           4.3          1.3  versicolor)
(('versicolor', 6.3),     sepal_length  sepal_width  petal_length  petal_width     species
56           6.3          3.3           4.7          1.6  versicolor
72           6.3          2.5           4.9          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor)
(('versicolor', 6.4),     sepal_length  sepal_width  petal_length  petal_width     species
51           6.4          3.2           4.5          1.5  versicolor
74           6.4          2.9           4.3          1.3  versicolor)
(('versicolor', 6.5),     sepal_length  sepal_width  petal_length  petal_width     species
54           6.5          2.8           4.6          1.5  versicolor)
(('versicolor', 6.6),     sepal_length  sepal_width  petal_length  petal_width     species
58           6.6          2.9           4.6          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor)
(('versicolor', 6.7),     sepal_length  sepal_width  petal_length  petal_width     species
65           6.7          3.1           4.4          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
86           6.7          3.1           4.7          1.5  versicolor)
(('versicolor', 6.8),     sepal_length  sepal_width  petal_length  petal_width     species
76           6.8          2.8           4.8          1.4  versicolor)
(('versicolor', 6.9),     sepal_length  sepal_width  petal_length  petal_width     species

52           6.9          3.1           4.9          1.5  versicolor)
(('versicolor', 7.0),     sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor)
(('virginica', 4.9),      sepal_length  sepal_width  petal_length  petal_width    species
106           4.9          2.5           4.5          1.7  virginica)
(('virginica', 5.6),      sepal_length  sepal_width  petal_length  petal_width    species
121           5.6          2.8           4.9          2.0  virginica)
(('virginica', 5.7),      sepal_length  sepal_width  petal_length  petal_width    species
113           5.7          2.5           5.0          2.0  virginica)
(('virginica', 5.8),      sepal_length  sepal_width  petal_length  petal_width    species
101           5.8          2.7           5.1          1.9  virginica
114           5.8          2.8           5.1          2.4  virginica
142           5.8          2.7           5.1          1.9  virginica)
(('virginica', 5.9),      sepal_length  sepal_width  petal_length  petal_width    species
149           5.9          3.0           5.1          1.8  virginica)
(('virginica', 6.0),      sepal_length  sepal_width  petal_length  petal_width    species
119           6.0          2.2           5.0          1.5  virginica
138           6.0          3.0           4.8          1.8  virginica)
(('virginica', 6.1),      sepal_length  sepal_width  petal_length  petal_width    species
127           6.1          3.0           4.9          1.8  virginica
134           6.1          2.6           5.6          1.4  virginica)
(('virginica', 6.2),      sepal_length  sepal_width  petal_length  petal_width    species
126           6.2          2.8           4.8          1.8  virginica
148           6.2          3.4           5.4          2.3  virginica)
(('virginica', 6.3),      sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
103           6.3          2.9           5.6          1.8  virginica
123           6.3          2.7           4.9          1.8  virginica
133           6.3          2.8           5.1          1.5  virginica
136           6.3          3.4           5.6          2.4  virginica
146           6.3          2.5           5.0          1.9  virginica)
(('virginica', 6.4),      sepal_length  sepal_width  petal_length  petal_width    species
111           6.4          2.7           5.3          1.9  virginica
115           6.4          3.2           5.3          2.3  virginica
128           6.4          2.8           5.6          2.1  virginica
132           6.4          2.8           5.6          2.2  virginica
137           6.4          3.1           5.5          1.8  virginica)
(('virginica', 6.5),      sepal_length  sepal_width  petal_length  petal_width    species
104           6.5          3.0           5.8          2.2  virginica
110           6.5          3.2           5.1          2.0  virginica
116           6.5          3.0           5.5          1.8  virginica
147           6.5          3.0           5.2          2.0  virginica)
(('virginica', 6.7),      sepal_length  sepal_width  petal_length  petal_width    species
108           6.7          2.5           5.8          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica)
(('virginica', 6.8),      sepal_length  sepal_width  petal_length  petal_width    species
112           6.8          3.0           5.5          2.1  virginica
143           6.8          3.2           5.9          2.3  virginica)
(('virginica', 6.9),      sepal_length  sepal_width  petal_length  petal_width    species
120           6.9          3.2           5.7          2.3  virginica
139           6.9          3.1           5.4          2.1  virginica
141           6.9          3.1           5.1          2.3  virginica)
(('virginica', 7.1),      sepal_length  sepal_width  petal_length  petal_width    species
102           7.1          3.0           5.9          2.1  virginica)
(('virginica', 7.2),      sepal_length  sepal_width  petal_length  petal_width    species
109           7.2          3.6           6.1          2.5  virginica
125           7.2          3.2           6.0          1.8  virginica
129           7.2          3.0           5.8          1.6  virginica)
(('virginica', 7.3),      sepal_length  sepal_width  petal_length  petal_width    species
107           7.3          2.9           6.3          1.8  virginica)
(('virginica', 7.4),      sepal_length  sepal_width  petal_length  petal_width    species
130           7.4          2.8           6.1          1.9  virginica)
(('virginica', 7.6),      sepal_length  sepal_width  petal_length  petal_width    species
105           7.6          3.0           6.6          2.1  virginica)
(('virginica', 7.7),      sepal_length  sepal_width  petal_length  petal_width    species
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica)
(('virginica', 7.9),      sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica)

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [89]:
iris.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [106]:
group_by_species.describe()

                        sepal_width                                        \
                              count      mean       std  min    25%   50%
species    sepal_length
setosa     4.3                  1.0  3.000000       NaN  3.0  3.000  3.00
           4.4                  3.0  3.033333  0.152753  2.9  2.950  3.00
           4.5                  1.0  2.300000       NaN  2.3  2.300  2.30
           4.6                  4.0  3.325000  0.221736  3.1  3.175  3.30
           4.7                  2.0  3.200000  0.000000  3.2  3.200  3.20
           4.8                  5.0  3.180000  0.204939  3.0  3.000  3.10
           4.9                  4.0  3.075000  0.050000  3.0  3.075  3.10
           5.0                  8.0  3.362500  0.192261  3.0  3.275  3.40
           5.1                  8.0  3.600000  0.200000  3.3  3.475  3.60
           5.2                  3.0  3.666667  0.378594  3.4  3.450  3.50
           5.3                  1.0  3.700000       NaN  3.7  3.700  3.70
           5.4                  5.0  3.660000  0.250998  3.4  3.400  3.70
           5.5                  2.0  3.850000  0.494975  3.5  3.675  3.85
           5.7                  2.0  4.100000  0.424264  3.8  3.950  4.10
           5.8                  1.0  4.000000       NaN  4.0  4.000  4.00
versicolor 4.9                  1.0  2.400000       NaN  2.4  2.400  2.40
           5.0                  2.0  2.150000  0.212132  2.0  2.075  2.15
           5.1                  1.0  2.500000       NaN  2.5  2.500  2.50
           5.2                  1.0  2.700000       NaN  2.7  2.700  2.70
           5.4                  1.0  3.000000       NaN  3.0  3.000  3.00
           5.5                  5.0  2.440000  0.114018  2.3  2.400  2.40
           5.6                  5.0  2.820000  0.216795  2.5  2.700  2.90
           5.7                  5.0  2.820000  0.148324  2.6  2.800  2.80
           5.8                  3.0  2.666667  0.057735  2.6  2.650  2.70
           5.9                  2.0  3.100000  0.141421  3.0  3.050  3.10
           6.0                  4.0  2.800000  0.496655  2.2  2.575  2.80
           6.1                  4.0  2.875000  0.095743  2.8  2.800  2.85
           6.2                  2.0  2.550000  0.494975  2.2  2.375  2.55
           6.3                  3.0  2.700000  0.529150  2.3  2.400  2.50
           6.4                  2.0  3.050000  0.212132  2.9  2.975  3.05
           6.5                  1.0  2.800000       NaN  2.8  2.800  2.80
           6.6                  2.0  2.950000  0.070711  2.9  2.925  2.95
           6.7                  3.0  3.066667  0.057735  3.0  3.050  3.10
           6.8                  1.0  2.800000       NaN  2.8  2.800  2.80
           6.9                  1.0  3.100000       NaN  3.1  3.100  3.10
           7.0                  1.0  3.200000       NaN  3.2  3.200  3.20
virginica  4.9                  1.0  2.500000       NaN  2.5  2.500  2.50
           5.6                  1.0  2.800000       NaN  2.8  2.800  2.80
           5.7                  1.0  2.500000       NaN  2.5  2.500  2.50
           5.8                  3.0  2.733333  0.057735  2.7  2.700  2.70
           5.9                  1.0  3.000000       NaN  3.0  3.000  3.00
           6.0                  2.0  2.600000  0.565685  2.2  2.400  2.60
           6.1                  2.0  2.800000  0.282843  2.6  2.700  2.80
           6.2                  2.0  3.100000  0.424264  2.8  2.950  3.10
           6.3                  6.0  2.933333  0.350238  2.5  2.725  2.85
           6.4                  5.0  2.920000  0.216795  2.7  2.800  2.80
           6.5                  4.0  3.050000  0.100000  3.0  3.000  3.00
           6.7                  5.0  3.040000  0.328634  2.5  3.000  3.10
           6.8                  2.0  3.100000  0.141421  3.0  3.050  3.10
           6.9                  3.0  3.133333  0.057735  3.1  3.100  3.10
           7.1                  1.0  3.000000       NaN  3.0  3.000  3.00
           7.2                  3.0  3.266667  0.305505  3.0  3.100  3.20
           7.3                  1.0  2.900000       NaN  2.9  2.900  2.90
           7.4                  1.0  2.800000       NaN  2.8  2.800  2.80
           7.6                  1.0  3.000000       NaN  3.0  3.000  3.00
           7.7                  4.0  3.050000  0.525991  2.6  2.750  2.90
           7.9                  1.0  3.800000       NaN  3.8  3.800  3.80

                                    petal_length            ...              \
                           75%  max        count      mean  ...    75%  max
species    sepal_length                                     ...
setosa     4.3           3.000  3.0          1.0  1.100000  ...  1.100  1.1
           4.4           3.100  3.2          3.0  1.333333  ...  1.350  1.4
           4.5           2.300  2.3          1.0  1.300000  ...  1.300  1.3
           4.6           3.450  3.6          4.0  1.325000  ...  1.425  1.5
           4.7           3.200  3.2          2.0  1.450000  ...  1.525  1.6
           4.8           3.400  3.4          5.0  1.580000  ...  1.600  1.9
           4.9           3.100  3.1          4.0  1.475000  ...  1.500  1.5
           5.0           3.500  3.6          8.0  1.450000  ...  1.600  1.6
           5.1           3.800  3.8          8.0  1.562500  ...  1.625  1.9
           5.2           3.800  4.1          3.0  1.466667  ...  1.500  1.5
           5.3           3.700  3.7          1.0  1.500000  ...  1.500  1.5
           5.4           3.900  3.9          5.0  1.540000  ...  1.700  1.7
           5.5           4.025  4.2          2.0  1.350000  ...  1.375  1.4
           5.7           4.250  4.4          2.0  1.600000  ...  1.650  1.7
           5.8           4.000  4.0          1.0  1.200000  ...  1.200  1.2
versicolor 4.9           2.400  2.4          1.0  3.300000  ...  3.300  3.3
           5.0           2.225  2.3          2.0  3.400000  ...  3.450  3.5
           5.1           2.500  2.5          1.0  3.000000  ...  3.000  3.0
           5.2           2.700  2.7          1.0  3.900000  ...  3.900  3.9
           5.4           3.000  3.0          1.0  4.500000  ...  4.500  4.5
           5.5           2.500  2.6          5.0  3.980000  ...  4.000  4.4
           5.6           3.000  3.0          5.0  4.060000  ...  4.200  4.5
           5.7           2.900  3.0          5.0  4.100000  ...  4.200  4.5
           5.8           2.700  2.7          3.0  4.000000  ...  4.050  4.1
           5.9           3.150  3.2          2.0  4.500000  ...  4.650  4.8
           6.0           3.025  3.4          4.0  4.525000  ...  4.650  5.1
           6.1           2.925  3.0          4.0  4.500000  ...  4.700  4.7
           6.2           2.725  2.9          2.0  4.400000  ...  4.450  4.5
           6.3           2.900  3.3          3.0  4.666667  ...  4.800  4.9
           6.4           3.125  3.2          2.0  4.400000  ...  4.450  4.5
           6.5           2.800  2.8          1.0  4.600000  ...  4.600  4.6
           6.6           2.975  3.0          2.0  4.500000  ...  4.550  4.6
           6.7           3.100  3.1          3.0  4.700000  ...  4.850  5.0
           6.8           2.800  2.8          1.0  4.800000  ...  4.800  4.8
           6.9           3.100  3.1          1.0  4.900000  ...  4.900  4.9
           7.0           3.200  3.2          1.0  4.700000  ...  4.700  4.7
virginica  4.9           2.500  2.5          1.0  4.500000  ...  4.500  4.5
           5.6           2.800  2.8          1.0  4.900000  ...  4.900  4.9
           5.7           2.500  2.5          1.0  5.000000  ...  5.000  5.0
           5.8           2.750  2.8          3.0  5.100000  ...  5.100  5.1
           5.9           3.000  3.0          1.0  5.100000  ...  5.100  5.1
           6.0           2.800  3.0          2.0  4.900000  ...  4.950  5.0
           6.1           2.900  3.0          2.0  5.250000  ...  5.425  5.6
           6.2           3.250  3.4          2.0  5.100000  ...  5.250  5.4
           6.3           3.200  3.4          6.0  5.366667  ...  5.600  6.0
           6.4           3.100  3.2          5.0  5.460000  ...  5.600  5.6
           6.5           3.050  3.2          4.0  5.400000  ...  5.575  5.8
           6.7           3.300  3.3          5.0  5.600000  ...  5.700  5.8
           6.8           3.150  3.2          2.0  5.700000  ...  5.800  5.9
           6.9           3.150  3.2          3.0  5.400000  ...  5.550  5.7
           7.1           3.000  3.0          1.0  5.900000  ...  5.900  5.9
           7.2           3.400  3.6          3.0  5.966667  ...  6.050  6.1
           7.3           2.900  2.9          1.0  6.300000  ...  6.300  6.3
           7.4           2.800  2.8          1.0  6.100000  ...  6.100  6.1
           7.6           3.000  3.0          1.0  6.600000  ...  6.600  6.6
           7.7           3.200  3.8          4.0  6.600000  ...  6.750  6.9
           7.9           3.800  3.8          1.0  6.400000  ...  6.400  6.4

                        petal_width                                            \
                              count      mean           std  min    25%   50%
species    sepal_length
setosa     4.3                  1.0  0.100000           NaN  0.1  0.100  0.10
           4.4                  3.0  0.200000  3.399350e-17  0.2  0.200  0.20
           4.5                  1.0  0.300000           NaN  0.3  0.300  0.30
           4.6                  4.0  0.225000  5.000000e-02  0.2  0.200  0.20
           4.7                  2.0  0.200000  0.000000e+00  0.2  0.200  0.20
           4.8                  5.0  0.200000  7.071068e-02  0.1  0.200  0.20
           4.9                  4.0  0.125000  5.000000e-02  0.1  0.100  0.10
           5.0                  8.0  0.287500  1.457738e-01  0.2  0.200  0.20
           5.1                  8.0  0.312500  1.125992e-01  0.2  0.200  0.30
           5.2                  3.0  0.166667  5.773503e-02  0.1  0.150  0.20
           5.3                  1.0  0.200000           NaN  0.2  0.200  0.20
           5.4                  5.0  0.320000  1.095445e-01  0.2  0.200  0.40
           5.5                  2.0  0.200000  0.000000e+00  0.2  0.200  0.20
           5.7                  2.0  0.350000  7.071068e-02  0.3  0.325  0.35
           5.8                  1.0  0.200000           NaN  0.2  0.200  0.20
versicolor 4.9                  1.0  1.000000           NaN  1.0  1.000  1.00
           5.0                  2.0  1.000000  0.000000e+00  1.0  1.000  1.00
           5.1                  1.0  1.100000           NaN  1.1  1.100  1.10
           5.2                  1.0  1.400000           NaN  1.4  1.400  1.40
           5.4                  1.0  1.500000           NaN  1.5  1.500  1.50
           5.5                  5.0  1.180000  1.303840e-01  1.0  1.100  1.20
           5.6                  5.0  1.300000  1.414214e-01  1.1  1.300  1.30
           5.7                  5.0  1.220000  1.303840e-01  1.0  1.200  1.30
           5.8                  3.0  1.133333  1.154701e-01  1.0  1.100  1.20
           5.9                  2.0  1.650000  2.121320e-01  1.5  1.575  1.65
           6.0                  4.0  1.425000  2.872281e-01  1.0  1.375  1.55
           6.1                  4.0  1.325000  9.574271e-02  1.2  1.275  1.35
           6.2                  2.0  1.400000  1.414214e-01  1.3  1.350  1.40
           6.3                  3.0  1.466667  1.527525e-01  1.3  1.400  1.50
           6.4                  2.0  1.400000  1.414214e-01  1.3  1.350  1.40
           6.5                  1.0  1.500000           NaN  1.5  1.500  1.50
           6.6                  2.0  1.350000  7.071068e-02  1.3  1.325  1.35
           6.7                  3.0  1.533333  1.527525e-01  1.4  1.450  1.50
           6.8                  1.0  1.400000           NaN  1.4  1.400  1.40
           6.9                  1.0  1.500000           NaN  1.5  1.500  1.50
           7.0                  1.0  1.400000           NaN  1.4  1.400  1.40
virginica  4.9                  1.0  1.700000           NaN  1.7  1.700  1.70
           5.6                  1.0  2.000000           NaN  2.0  2.000  2.00
           5.7                  1.0  2.000000           NaN  2.0  2.000  2.00
           5.8                  3.0  2.066667  2.886751e-01  1.9  1.900  1.90
           5.9                  1.0  1.800000           NaN  1.8  1.800  1.80
           6.0                  2.0  1.650000  2.121320e-01  1.5  1.575  1.65
           6.1                  2.0  1.600000  2.828427e-01  1.4  1.500  1.60
           6.2                  2.0  2.050000  3.535534e-01  1.8  1.925  2.05
           6.3                  6.0  1.983333  3.868678e-01  1.5  1.800  1.85
           6.4                  5.0  2.060000  2.073644e-01  1.8  1.900  2.10
           6.5                  4.0  2.000000  1.632993e-01  1.8  1.950  2.00
           6.7                  5.0  2.220000  2.774887e-01  1.8  2.100  2.30
           6.8                  2.0  2.200000  1.414214e-01  2.1  2.150  2.20
           6.9                  3.0  2.233333  1.154701e-01  2.1  2.200  2.30
           7.1                  1.0  2.100000           NaN  2.1  2.100  2.10
           7.2                  3.0  1.966667  4.725816e-01  1.6  1.700  1.80
           7.3                  1.0  1.800000           NaN  1.8  1.800  1.80
           7.4                  1.0  1.900000           NaN  1.9  1.900  1.90
           7.6                  1.0  2.100000           NaN  2.1  2.100  2.10
           7.7                  4.0  2.200000  1.414214e-01  2.0  2.150  2.25
           7.9                  1.0  2.000000           NaN  2.0  2.000  2.00


                           75%  max
species    sepal_length
setosa     4.3           0.100  0.1
           4.4           0.200  0.2
           4.5           0.300  0.3
           4.6           0.225  0.3
           4.7           0.200  0.2
           4.8           0.200  0.3
           4.9           0.125  0.2
           5.0           0.325  0.6
           5.1           0.400  0.5
           5.2           0.200  0.2
           5.3           0.200  0.2
           5.4           0.400  0.4
           5.5           0.200  0.2
           5.7           0.375  0.4
           5.8           0.200  0.2
versicolor 4.9           1.000  1.0
           5.0           1.000  1.0
           5.1           1.100  1.1
           5.2           1.400  1.4
           5.4           1.500  1.5
           5.5           1.300  1.3
           5.6           1.300  1.5
           5.7           1.300  1.3
           5.8           1.200  1.2
           5.9           1.725  1.8
           6.0           1.600  1.6
           6.1           1.400  1.4
           6.2           1.450  1.5
           6.3           1.550  1.6
           6.4           1.450  1.5
           6.5           1.500  1.5
           6.6           1.375  1.4
           6.7           1.600  1.7
           6.8           1.400  1.4
           6.9           1.500  1.5
           7.0           1.400  1.4
virginica  4.9           1.700  1.7
           5.6           2.000  2.0
           5.7           2.000  2.0
           5.8           2.150  2.4
           5.9           1.800  1.8
           6.0           1.725  1.8
           6.1           1.700  1.8
           6.2           2.175  2.3
           6.3           2.275  2.5
           6.4           2.200  2.3
           6.5           2.050  2.2
           6.7           2.400  2.5
           6.8           2.250  2.3
           6.9           2.300  2.3
           7.1           2.100  2.1
           7.2           2.150  2.5
           7.3           1.800  1.8
           7.4           1.900  1.9
           7.6           2.100  2.1
           7.7           2.300  2.3
           7.9           2.000  2.0

[57 rows x 24 columns]

In [93]:
iris[iris['species']=='setosa']

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

## Using the Iris dataset, do the following:

- Add a rank column to the iris DataFrame, ranking the petal length in an ascending order
- Find the mean of each column for each species
- Create a new DataFrame for each of the species separately - should have 3 in total, make sure each index starts at 0
- Create two final DataFrames: One for the Sepal information, and one for the Petal information. This should be done on the whole dataset so that in each DataFrame we have information about all three species

In [128]:
pd.set_option('display.max_rows', 1000, 'display.max_columns', 1000)

In [119]:
iris2 = pd.read_csv("iris.csv")
iris2

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [120]:
iris2.sort_values(by=["petal_length"], ascending=True)

     sepal_length  sepal_width  petal_length  petal_width    species
22            4.6          3.6           1.0          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
35            5.0          3.2           1.2          0.2     setosa
36            5.5          3.5           1.3          0.2     setosa
..            ...          ...           ...          ...        ...
131           7.9          3.8           6.4          2.0  virginica
105           7.6          3.0           6.6          2.1  virginica
117           7.7          3.8           6.7          2.2  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica

[150 rows x 5 columns]

In [136]:
iris2["Rank"] = iris["petal_length"].rank(ascending=True, method="max")
print(iris2.sort_values(by=["Rank"], ascending=True))

     sepal_length  sepal_width  petal_length  petal_width     species   Rank
22            4.6          3.6           1.0          0.2      setosa    1.0
13            4.3          3.0           1.1          0.1      setosa    2.0
14            5.8          4.0           1.2          0.2      setosa    4.0
35            5.0          3.2           1.2          0.2      setosa    4.0
36            5.5          3.5           1.3          0.2      setosa   11.0
40            5.0          3.5           1.3          0.3      setosa   11.0
38            4.4          3.0           1.3          0.2      setosa   11.0
42            4.4          3.2           1.3          0.2      setosa   11.0
2             4.7          3.2           1.3          0.2      setosa   11.0
41            4.5          2.3           1.3          0.3      setosa   11.0
16            5.4          3.9           1.3          0.4      setosa   11.0
17            5.1          3.5           1.4          0.3      setosa   23.0
45            4.8          3.0           1.4          0.3      setosa   23.0
33            5.5          4.2           1.4          0.2      setosa   23.0
28            5.2          3.4           1.4          0.2      setosa   23.0
47            4.6          3.2           1.4          0.2      setosa   23.0
49            5.0          3.3           1.4          0.2      setosa   23.0
0             5.1          3.5           1.4          0.2      setosa   23.0
4             5.0          3.6           1.4          0.2      setosa   23.0
1             4.9          3.0           1.4          0.2      setosa   23.0
12            4.8          3.0           1.4          0.1      setosa   23.0
6             4.6          3.4           1.4          0.3      setosa   23.0
8             4.4          2.9           1.4          0.2      setosa   23.0
34            4.9          3.1           1.5          0.1      setosa   37.0
10            5.4          3.7           1.5          0.2      setosa   37.0
32            5.2          4.1           1.5          0.1      setosa   37.0
31            5.4          3.4           1.5          0.4      setosa   37.0
15            5.7          4.4           1.5          0.4      setosa   37.0
27            5.2          3.5           1.5          0.2      setosa   37.0
9             4.9          3.1           1.5          0.1      setosa   37.0
7             5.0          3.4           1.5          0.2      setosa   37.0
3             4.6          3.1           1.5          0.2      setosa   37.0
48            5.3          3.7           1.5          0.2      setosa   37.0
21            5.1          3.7           1.5          0.4      setosa   37.0
19            5.1          3.8           1.5          0.3      setosa   37.0
39            5.1          3.4           1.5          0.2      setosa   37.0
37            4.9          3.1           1.5          0.1      setosa   37.0
30            4.8          3.1           1.6          0.2      setosa   44.0
29            4.7          3.2           1.6          0.2      setosa   44.0
11            4.8          3.4           1.6          0.2      setosa   44.0
26            5.0          3.4           1.6          0.4      setosa   44.0
25            5.0          3.0           1.6          0.2      setosa   44.0
46            5.1          3.8           1.6          0.2      setosa   44.0
43            5.0          3.5           1.6          0.6      setosa   44.0
18            5.7          3.8           1.7          0.3      setosa   48.0
5             5.4          3.9           1.7          0.4      setosa   48.0
23            5.1          3.3           1.7          0.5      setosa   48.0
20            5.4          3.4           1.7          0.2      setosa   48.0
24            4.8          3.4           1.9          0.2      setosa   50.0
44            5.1          3.8           1.9          0.4      setosa   50.0
98            5.1          2.5           3.0          1.1  versicolor   51.0
93            5.0          2.3           3.3          1.0  versicolor   53.0
57            4.9          2.4           3.3          1.0  versicolor   53.0
60            5.0          2.0           3.5          1.0  versicolor   55.0
79            5.7          2.6           3.5          1.0  versicolor   55.0
64            5.6          2.9           3.6          1.3  versicolor   56.0
81            5.5          2.4           3.7          1.0  versicolor   57.0
80            5.5          2.4           3.8          1.1  versicolor   58.0
69            5.6          2.5           3.9          1.1  versicolor   61.0
82            5.8          2.7           3.9          1.2  versicolor   61.0
59            5.2          2.7           3.9          1.4  versicolor   61.0
62            6.0          2.2           4.0          1.0  versicolor   66.0
92            5.8          2.6           4.0          1.2  versicolor   66.0
89            5.5          2.5           4.0          1.3  versicolor   66.0
53            5.5          2.3           4.0          1.3  versicolor   66.0
71            6.1          2.8           4.0          1.3  versicolor   66.0
88            5.6          3.0           4.1          1.3  versicolor   69.0
67            5.8          2.7           4.1          1.0  versicolor   69.0
99            5.7          2.8           4.1          1.3  versicolor   69.0
61            5.9          3.0           4.2          1.5  versicolor   73.0
96            5.7          2.9           4.2          1.3  versicolor   73.0
94            5.6          2.7           4.2          1.3  versicolor   73.0
95            5.7          3.0           4.2          1.2  versicolor   73.0
97            6.2          2.9           4.3          1.3  versicolor   75.0
74            6.4          2.9           4.3          1.3  versicolor   75.0
75            6.6          3.0           4.4          1.4  versicolor   79.0
90            5.5          2.6           4.4          1.2  versicolor   79.0
65            6.7          3.1           4.4          1.4  versicolor   79.0
87            6.3          2.3           4.4          1.3  versicolor   79.0
106           4.9          2.5           4.5          1.7   virginica   87.0
51            6.4          3.2           4.5          1.5  versicolor   87.0
78            6.0          2.9           4.5          1.5  versicolor   87.0
55            5.7          2.8           4.5          1.3  versicolor   87.0
68            6.2          2.2           4.5          1.5  versicolor   87.0
84            5.4          3.0           4.5          1.5  versicolor   87.0
85            6.0          3.4           4.5          1.6  versicolor   87.0
66            5.6          3.0           4.5          1.5  versicolor   87.0
54            6.5          2.8           4.6          1.5  versicolor   90.0
91            6.1          3.0           4.6          1.4  versicolor   90.0
58            6.6          2.9           4.6          1.3  versicolor   90.0
63            6.1          2.9           4.7          1.4  versicolor   95.0
56            6.3          3.3           4.7          1.6  versicolor   95.0
73            6.1          2.8           4.7          1.2  versicolor   95.0
50            7.0          3.2           4.7          1.4  versicolor   95.0
86            6.7          3.1           4.7          1.5  versicolor   95.0
70            5.9          3.2           4.8          1.8  versicolor   99.0
138           6.0          3.0           4.8          1.8   virginica   99.0
76            6.8          2.8           4.8          1.4  versicolor   99.0
126           6.2          2.8           4.8          1.8   virginica   99.0
72            6.3          2.5           4.9          1.5  versicolor  104.0
52            6.9          3.1           4.9          1.5  versicolor  104.0
121           5.6          2.8           4.9          2.0   virginica  104.0
123           6.3          2.7           4.9          1.8   virginica  104.0
127           6.1          3.0           4.9          1.8   virginica  104.0
146           6.3          2.5           5.0          1.9   virginica  108.0
119           6.0          2.2           5.0          1.5   virginica  108.0
113           5.7          2.5           5.0          2.0   virginica  108.0
77            6.7          3.0           5.0          1.7  versicolor  108.0
141           6.9          3.1           5.1          2.3   virginica  116.0
114           5.8          2.8           5.1          2.4   virginica  116.0
133           6.3          2.8           5.1          1.5   virginica  116.0
142           5.8          2.7           5.1          1.9   virginica  116.0
149           5.9          3.0           5.1          1.8   virginica  116.0
110           6.5          3.2           5.1          2.0   virginica  116.0
83            6.0          2.7           5.1          1.6  versicolor  116.0
101           5.8          2.7           5.1          1.9   virginica  116.0
147           6.5          3.0           5.2          2.0   virginica  118.0
145           6.7          3.0           5.2          2.3   virginica  118.0
111           6.4          2.7           5.3          1.9   virginica  120.0
115           6.4          3.2           5.3          2.3   virginica  120.0
139           6.9          3.1           5.4          2.1   virginica  122.0
148           6.2          3.4           5.4          2.3   virginica  122.0
137           6.4          3.1           5.5          1.8   virginica  125.0
112           6.8          3.0           5.5          2.1   virginica  125.0
116           6.5          3.0           5.5          1.8   virginica  125.0
136           6.3          3.4           5.6          2.4   virginica  131.0
140           6.7          3.1           5.6          2.4   virginica  131.0
128           6.4          2.8           5.6          2.1   virginica  131.0
134           6.1          2.6           5.6          1.4   virginica  131.0
103           6.3          2.9           5.6          1.8   virginica  131.0
132           6.4          2.8           5.6          2.2   virginica  131.0
144           6.7          3.3           5.7          2.5   virginica  134.0
120           6.9          3.2           5.7          2.3   virginica  134.0
124           6.7          3.3           5.7          2.1   virginica  134.0
108           6.7          2.5           5.8          1.8   virginica  137.0
129           7.2          3.0           5.8          1.6   virginica  137.0
104           6.5          3.0           5.8          2.2   virginica  137.0
102           7.1          3.0           5.9          2.1   virginica  139.0
143           6.8          3.2           5.9          2.3   virginica  139.0
100           6.3          3.3           6.0          2.5   virginica  141.0
125           7.2          3.2           6.0          1.8   virginica  141.0
130           7.4          2.8           6.1          1.9   virginica  144.0
135           7.7          3.0           6.1          2.3   virginica  144.0
109           7.2          3.6           6.1          2.5   virginica  144.0
107           7.3          2.9           6.3          1.8   virginica  145.0
131           7.9          3.8           6.4          2.0   virginica  146.0
105           7.6          3.0           6.6          2.1   virginica  147.0
117           7.7          3.8           6.7          2.2   virginica  149.0
122           7.7          2.8           6.7          2.0   virginica  149.0
118           7.7          2.6           6.9          2.3   virginica  150.0

In [126]:
iris3 = pd.read_csv("iris.csv")

In [127]:
means = iris3.groupby(by=["species"], axis=0).mean()
means

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [141]:
setosa_df = iris3[iris3['species'] =='setosa'].reset_index()
versicolor_df = iris3[iris3['species'] =='versicolor'].reset_index()
virginica_df = iris3[iris3['species'] =='virginica'].reset_index()

In [142]:
virginica_df

    index  sepal_length  sepal_width  petal_length  petal_width    species
0     100           6.3          3.3           6.0          2.5  virginica
1     101           5.8          2.7           5.1          1.9  virginica
2     102           7.1          3.0           5.9          2.1  virginica
3     103           6.3          2.9           5.6          1.8  virginica
4     104           6.5          3.0           5.8          2.2  virginica
5     105           7.6          3.0           6.6          2.1  virginica
6     106           4.9          2.5           4.5          1.7  virginica
7     107           7.3          2.9           6.3          1.8  virginica
8     108           6.7          2.5           5.8          1.8  virginica
9     109           7.2          3.6           6.1          2.5  virginica
10    110           6.5          3.2           5.1          2.0  virginica
11    111           6.4          2.7           5.3          1.9  virginica
12    112           6.8          3.0           5.5          2.1  virginica
13    113           5.7          2.5           5.0          2.0  virginica
14    114           5.8          2.8           5.1          2.4  virginica
15    115           6.4          3.2           5.3          2.3  virginica
16    116           6.5          3.0           5.5          1.8  virginica
17    117           7.7          3.8           6.7          2.2  virginica
18    118           7.7          2.6           6.9          2.3  virginica
19    119           6.0          2.2           5.0          1.5  virginica
20    120           6.9          3.2           5.7          2.3  virginica
21    121           5.6          2.8           4.9          2.0  virginica
22    122           7.7          2.8           6.7          2.0  virginica
23    123           6.3          2.7           4.9          1.8  virginica
24    124           6.7          3.3           5.7          2.1  virginica
25    125           7.2          3.2           6.0          1.8  virginica
26    126           6.2          2.8           4.8          1.8  virginica
27    127           6.1          3.0           4.9          1.8  virginica
28    128           6.4          2.8           5.6          2.1  virginica
29    129           7.2          3.0           5.8          1.6  virginica
30    130           7.4          2.8           6.1          1.9  virginica
31    131           7.9          3.8           6.4          2.0  virginica
32    132           6.4          2.8           5.6          2.2  virginica
33    133           6.3          2.8           5.1          1.5  virginica
34    134           6.1          2.6           5.6          1.4  virginica
35    135           7.7          3.0           6.1          2.3  virginica
36    136           6.3          3.4           5.6          2.4  virginica
37    137           6.4          3.1           5.5          1.8  virginica
38    138           6.0          3.0           4.8          1.8  virginica
39    139           6.9          3.1           5.4          2.1  virginica
40    140           6.7          3.1           5.6          2.4  virginica
41    141           6.9          3.1           5.1          2.3  virginica
42    142           5.8          2.7           5.1          1.9  virginica
43    143           6.8          3.2           5.9          2.3  virginica
44    144           6.7          3.3           5.7          2.5  virginica
45    145           6.7          3.0           5.2          2.3  virginica
46    146           6.3          2.5           5.0          1.9  virginica
47    147           6.5          3.0           5.2          2.0  virginica
48    148           6.2          3.4           5.4          2.3  virginica
49    149           5.9          3.0           5.1          1.8  virginica

Create two final DataFrames: One for the Sepal information, and one for the Petal information. This should be done on the whole dataset so that in each DataFrame we have information about all three species

In [145]:
sepal = iris3[["species","sepal_length","sepal_width"]]
sepal

        species  sepal_length  sepal_width
0        setosa           5.1          3.5
1        setosa           4.9          3.0
2        setosa           4.7          3.2
3        setosa           4.6          3.1
4        setosa           5.0          3.6
5        setosa           5.4          3.9
6        setosa           4.6          3.4
7        setosa           5.0          3.4
8        setosa           4.4          2.9
9        setosa           4.9          3.1
10       setosa           5.4          3.7
11       setosa           4.8          3.4
12       setosa           4.8          3.0
13       setosa           4.3          3.0
14       setosa           5.8          4.0
15       setosa           5.7          4.4
16       setosa           5.4          3.9
17       setosa           5.1          3.5
18       setosa           5.7          3.8
19       setosa           5.1          3.8
20       setosa           5.4          3.4
21       setosa           5.1          3.7
22       setosa           4.6          3.6
23       setosa           5.1          3.3
24       setosa           4.8          3.4
25       setosa           5.0          3.0
26       setosa           5.0          3.4
27       setosa           5.2          3.5
28       setosa           5.2          3.4
29       setosa           4.7          3.2
30       setosa           4.8          3.1
31       setosa           5.4          3.4
32       setosa           5.2          4.1
33       setosa           5.5          4.2
34       setosa           4.9          3.1
35       setosa           5.0          3.2
36       setosa           5.5          3.5
37       setosa           4.9          3.1
38       setosa           4.4          3.0
39       setosa           5.1          3.4
40       setosa           5.0          3.5
41       setosa           4.5          2.3
42       setosa           4.4          3.2
43       setosa           5.0          3.5
44       setosa           5.1          3.8
45       setosa           4.8          3.0
46       setosa           5.1          3.8
47       setosa           4.6          3.2
48       setosa           5.3          3.7
49       setosa           5.0          3.3
50   versicolor           7.0          3.2
51   versicolor           6.4          3.2
52   versicolor           6.9          3.1
53   versicolor           5.5          2.3
54   versicolor           6.5          2.8
55   versicolor           5.7          2.8
56   versicolor           6.3          3.3
57   versicolor           4.9          2.4
58   versicolor           6.6          2.9
59   versicolor           5.2          2.7
60   versicolor           5.0          2.0
61   versicolor           5.9          3.0
62   versicolor           6.0          2.2
63   versicolor           6.1          2.9
64   versicolor           5.6          2.9
65   versicolor           6.7          3.1
66   versicolor           5.6          3.0
67   versicolor           5.8          2.7
68   versicolor           6.2          2.2
69   versicolor           5.6          2.5
70   versicolor           5.9          3.2
71   versicolor           6.1          2.8
72   versicolor           6.3          2.5
73   versicolor           6.1          2.8
74   versicolor           6.4          2.9
75   versicolor           6.6          3.0
76   versicolor           6.8          2.8
77   versicolor           6.7          3.0
78   versicolor           6.0          2.9
79   versicolor           5.7          2.6
80   versicolor           5.5          2.4
81   versicolor           5.5          2.4
82   versicolor           5.8          2.7
83   versicolor           6.0          2.7
84   versicolor           5.4          3.0
85   versicolor           6.0          3.4
86   versicolor           6.7          3.1
87   versicolor           6.3          2.3
88   versicolor           5.6          3.0
89   versicolor           5.5          2.5
90   versicolor           5.5          2.6
91   versicolor           6.1          3.0
92   versicolor           5.8          2.6
93   versicolor           5.0          2.3
94   versicolor           5.6          2.7
95   versicolor           5.7          3.0
96   versicolor           5.7          2.9
97   versicolor           6.2          2.9
98   versicolor           5.1          2.5
99   versicolor           5.7          2.8
100   virginica           6.3          3.3
101   virginica           5.8          2.7
102   virginica           7.1          3.0
103   virginica           6.3          2.9
104   virginica           6.5          3.0
105   virginica           7.6          3.0
106   virginica           4.9          2.5
107   virginica           7.3          2.9
108   virginica           6.7          2.5
109   virginica           7.2          3.6
110   virginica           6.5          3.2
111   virginica           6.4          2.7
112   virginica           6.8          3.0
113   virginica           5.7          2.5
114   virginica           5.8          2.8
115   virginica           6.4          3.2
116   virginica           6.5          3.0
117   virginica           7.7          3.8
118   virginica           7.7          2.6
119   virginica           6.0          2.2
120   virginica           6.9          3.2
121   virginica           5.6          2.8
122   virginica           7.7          2.8
123   virginica           6.3          2.7
124   virginica           6.7          3.3
125   virginica           7.2          3.2
126   virginica           6.2          2.8
127   virginica           6.1          3.0
128   virginica           6.4          2.8
129   virginica           7.2          3.0
130   virginica           7.4          2.8
131   virginica           7.9          3.8
132   virginica           6.4          2.8
133   virginica           6.3          2.8
134   virginica           6.1          2.6
135   virginica           7.7          3.0
136   virginica           6.3          3.4
137   virginica           6.4          3.1
138   virginica           6.0          3.0
139   virginica           6.9          3.1
140   virginica           6.7          3.1
141   virginica           6.9          3.1
142   virginica           5.8          2.7
143   virginica           6.8          3.2
144   virginica           6.7          3.3
145   virginica           6.7          3.0
146   virginica           6.3          2.5
147   virginica           6.5          3.0
148   virginica           6.2          3.4
149   virginica           5.9          3.0

In [147]:
petal = iris3[["species", "petal_length", "petal_width"]]
petal

        species  petal_length  petal_width
0        setosa           1.4          0.2
1        setosa           1.4          0.2
2        setosa           1.3          0.2
3        setosa           1.5          0.2
4        setosa           1.4          0.2
5        setosa           1.7          0.4
6        setosa           1.4          0.3
7        setosa           1.5          0.2
8        setosa           1.4          0.2
9        setosa           1.5          0.1
10       setosa           1.5          0.2
11       setosa           1.6          0.2
12       setosa           1.4          0.1
13       setosa           1.1          0.1
14       setosa           1.2          0.2
15       setosa           1.5          0.4
16       setosa           1.3          0.4
17       setosa           1.4          0.3
18       setosa           1.7          0.3
19       setosa           1.5          0.3
20       setosa           1.7          0.2
21       setosa           1.5          0.4
22       setosa           1.0          0.2
23       setosa           1.7          0.5
24       setosa           1.9          0.2
25       setosa           1.6          0.2
26       setosa           1.6          0.4
27       setosa           1.5          0.2
28       setosa           1.4          0.2
29       setosa           1.6          0.2
30       setosa           1.6          0.2
31       setosa           1.5          0.4
32       setosa           1.5          0.1
33       setosa           1.4          0.2
34       setosa           1.5          0.1
35       setosa           1.2          0.2
36       setosa           1.3          0.2
37       setosa           1.5          0.1
38       setosa           1.3          0.2
39       setosa           1.5          0.2
40       setosa           1.3          0.3
41       setosa           1.3          0.3
42       setosa           1.3          0.2
43       setosa           1.6          0.6
44       setosa           1.9          0.4
45       setosa           1.4          0.3
46       setosa           1.6          0.2
47       setosa           1.4          0.2
48       setosa           1.5          0.2
49       setosa           1.4          0.2
50   versicolor           4.7          1.4
51   versicolor           4.5          1.5
52   versicolor           4.9          1.5
53   versicolor           4.0          1.3
54   versicolor           4.6          1.5
55   versicolor           4.5          1.3
56   versicolor           4.7          1.6
57   versicolor           3.3          1.0
58   versicolor           4.6          1.3
59   versicolor           3.9          1.4
60   versicolor           3.5          1.0
61   versicolor           4.2          1.5
62   versicolor           4.0          1.0
63   versicolor           4.7          1.4
64   versicolor           3.6          1.3
65   versicolor           4.4          1.4
66   versicolor           4.5          1.5
67   versicolor           4.1          1.0
68   versicolor           4.5          1.5
69   versicolor           3.9          1.1
70   versicolor           4.8          1.8
71   versicolor           4.0          1.3
72   versicolor           4.9          1.5
73   versicolor           4.7          1.2
74   versicolor           4.3          1.3
75   versicolor           4.4          1.4
76   versicolor           4.8          1.4
77   versicolor           5.0          1.7
78   versicolor           4.5          1.5
79   versicolor           3.5          1.0
80   versicolor           3.8          1.1
81   versicolor           3.7          1.0
82   versicolor           3.9          1.2
83   versicolor           5.1          1.6
84   versicolor           4.5          1.5
85   versicolor           4.5          1.6
86   versicolor           4.7          1.5
87   versicolor           4.4          1.3
88   versicolor           4.1          1.3
89   versicolor           4.0          1.3
90   versicolor           4.4          1.2
91   versicolor           4.6          1.4
92   versicolor           4.0          1.2
93   versicolor           3.3          1.0
94   versicolor           4.2          1.3
95   versicolor           4.2          1.2
96   versicolor           4.2          1.3
97   versicolor           4.3          1.3
98   versicolor           3.0          1.1
99   versicolor           4.1          1.3
100   virginica           6.0          2.5
101   virginica           5.1          1.9
102   virginica           5.9          2.1
103   virginica           5.6          1.8
104   virginica           5.8          2.2
105   virginica           6.6          2.1
106   virginica           4.5          1.7
107   virginica           6.3          1.8
108   virginica           5.8          1.8
109   virginica           6.1          2.5
110   virginica           5.1          2.0
111   virginica           5.3          1.9
112   virginica           5.5          2.1
113   virginica           5.0          2.0
114   virginica           5.1          2.4
115   virginica           5.3          2.3
116   virginica           5.5          1.8
117   virginica           6.7          2.2
118   virginica           6.9          2.3
119   virginica           5.0          1.5
120   virginica           5.7          2.3
121   virginica           4.9          2.0
122   virginica           6.7          2.0
123   virginica           4.9          1.8
124   virginica           5.7          2.1
125   virginica           6.0          1.8
126   virginica           4.8          1.8
127   virginica           4.9          1.8
128   virginica           5.6          2.1
129   virginica           5.8          1.6
130   virginica           6.1          1.9
131   virginica           6.4          2.0
132   virginica           5.6          2.2
133   virginica           5.1          1.5
134   virginica           5.6          1.4
135   virginica           6.1          2.3
136   virginica           5.6          2.4
137   virginica           5.5          1.8
138   virginica           4.8          1.8
139   virginica           5.4          2.1
140   virginica           5.6          2.4
141   virginica           5.1          2.3
142   virginica           5.1          1.9
143   virginica           5.9          2.3
144   virginica           5.7          2.5
145   virginica           5.2          2.3
146   virginica           5.0          1.9
147   virginica           5.2          2.0
148   virginica           5.4          2.3
149   virginica           5.1          1.8

#### merge and concat to get back to the same kind of dataframe

In [190]:
frames = [sepal, petal]
reverse = pd.concat(frames, axis=1, join="outer")
reverse

,species,sepal_length,sepal_width,species,petal_length,petal_width
0,setosa,5.1,3.5,setosa,1.4,0.2
1,setosa,4.9,3.0,setosa,1.4,0.2
2,setosa,4.7,3.2,setosa,1.3,0.2
3,setosa,4.6,3.1,setosa,1.5,0.2
4,setosa,5.0,3.6,setosa,1.4,0.2
5,setosa,5.4,3.9,setosa,1.7,0.4
6,setosa,4.6,3.4,setosa,1.4,0.3
7,setosa,5.0,3.4,setosa,1.5,0.2
8,setosa,4.4,2.9,setosa,1.4,0.2
9,setosa,4.9,3.1,setosa,1.5,0.1
10,setosa,5.4,3.7,setosa,1.5,0.2
11,setosa,4.8,3.4,setosa,1.6,0.2
12,setosa,4.8,3.0,setosa,1.4,0.1
13,setosa,4.3,3.0,setosa,1.1,0.1
14,setosa,5.8,4.0,setosa,1.2,0.2
15,setosa,5.7,4.4,setosa,1.5,0.4
16,setosa,5.4,3.9,setosa,1.3,0.4
17,setosa,5.1,3.5,setosa,1.4,0.3
18,setosa,5.7,3.8,setosa,1.7,0.3
19,setosa,5.1,3.8,setosa,1.5,0.3
20,setosa,5.4,3.4,setosa,1.7,0.2
21,setosa,5.1,3.7,setosa,1.5,0.4
22,setosa,4.6,3.6,setosa,1.0,0.2
23,setosa,5.1,3.3,setosa,1.7,0.5
24,setosa,4.8,3.4,setosa,1.9,0.2
25,setosa,5.0,3.0,setosa,1.6,0.2
26,setosa,5.0,3.4,setosa,1.6,0.4
27,setosa,5.2,3.5,setosa,1.5,0.2
28,setosa,5.2,3.4,setosa,1.4,0.2
29,setosa,4.7,3.2,setosa,1.6,0.2
30,setosa,4.8,3.1,setosa,1.6,0.2
31,setosa,5.4,3.4,setosa,1.5,0.4
32,setosa,5.2,4.1,setosa,1.5,0.1
33,setosa,5.5,4.2,setosa,1.4,0.2
34,setosa,4.9,3.1,setosa,1.5,0.1
35,setosa,5.0,3.2,setosa,1.2,0.2
36,setosa,5.5,3.5,setosa,1.3,0.2
37,setosa,4.9,3.1,setosa,1.5,0.1
38,setosa,4.4,3.0,setosa,1.3,0.2
39,setosa,5.1,3.4,setosa,1.5,0.2
40,setosa,5.0,3.5,setosa,1.3,0.3
41,setosa,4.5,2.3,setosa,1.3,0.3
42,setosa,4.4,3.2,setosa,1.3,0.2
43,setosa,5.0,3.5,setosa,1.6,0.6
44,setosa,5.1,3.8,setosa,1.9,0.4
45,setosa,4.8,3.0,setosa,1.4,0.3
46,setosa,5.1,3.8,setosa,1.6,0.2
47,setosa,4.6,3.2,setosa,1.4,0.2
48,setosa,5.3,3.7,setosa,1.5,0.2
49,setosa,5.0,3.3,setosa,1.4,0.2
50,versicolor,7.0,3.2,versicolor,4.7,1.4
51,versicolor,6.4,3.2,versicolor,4.5,1.5
52,versicolor,6.9,3.1,versicolor,4.9,1.5
53,versicolor,5.5,2.3,versicolor,4.0,1.3
54,versicolor,6.5,2.8,versicolor,4.6,1.5
55,versicolor,5.7,2.8,versicolor,4.5,1.3
56,versicolor,6.3,3.3,versicolor,4.7,1.6
57,versicolor,4.9,2.4,versicolor,3.3,1.0
58,versicolor,6.6,2.9,versicolor,4.6,1.3
59,versicolor,5.2,2.7,versicolor,3.9,1.4
60,versicolor,5.0,2.0,versicolor,3.5,1.0
61,versicolor,5.9,3.0,versicolor,4.2,1.5
62,versicolor,6.0,2.2,versicolor,4.0,1.0
63,versicolor,6.1,2.9,versicolor,4.7,1.4
64,versicolor,5.6,2.9,versicolor,3.6,1.3
65,versicolor,6.7,3.1,versicolor,4.4,1.4
66,versicolor,5.6,3.0,versicolor,4.5,1.5
67,versicolor,5.8,2.7,versicolor,4.1,1.0
68,versicolor,6.2,2.2,versicolor,4.5,1.5
69,versicolor,5.6,2.5,versicolor,3.9,1.1
70,versicolor,5.9,3.2,versicolor,4.8,1.8
71,versicolor,6.1,2.8,versicolor,4.0,1.3
72,versicolor,6.3,2.5,versicolor,4.9,1.5
73,versicolor,6.1,2.8,versicolor,4.7,1.2
74,versicolor,6.4,2.9,versicolor,4.3,1.3
75,versicolor,6.6,3.0,versicolor,4.4,1.4
76,versicolor,6.8,2.8,versicolor,4.8,1.4
77,versicolor,6.7,3.0,versicolor,5.0,1.7
78,versicolor,6.0,2.9,versicolor,4.5,1.5
79,versicolor,5.7,2.6,versicolor,3.5,1.0
80,versicolor,5.5,2.4,versicolor,3.8,1.1
81,versicolor,5.5,2.4,versicolor,3.7,1.0
82,versicolor,5.8,2.7,versicolor,3.9,1.2
83,versicolor,6.0,2.7,versicolor,5.1,1.6
84,versicolor,5.4,3.0,versicolor,4.5,1.5
85,versicolor,6.0,3.4,versicolor,4.5,1.6
86,versicolor,6.7,3.1,versicolor,4.7,1.5
87,versicolor,6.3,2.3,versicolor,4.4,1.3
88,versicolor,5.6,3.0,versicolor,4.1,1.3
89,versicolor,5.5,2.5,versicolor,4.0,1.3
90,versicolor,5.5,2.6,versicolor,4.4,1.2
91,versicolor,6.1,3.0,versicolor,4.6,1.4
92,versicolor,5.8,2.6,versicolor,4.0,1.2
93,versicolor,5.0,2.3,versicolor,3.3,1.0
94,versicolor,5.6,2.7,versicolor,4.2,1.3
95,versicolor,5.7,3.0,versicolor,4.2,1.2
96,versicolor,5.7,2.9,versicolor,4.2,1.3
97,versicolor,6.2,2.9,versicolor,4.3,1.3
98,versicolor,5.1,2.5,versicolor,3.0,1.1
99,versicolor,5.7,2.8,versicolor,4.1,1.3
100,virginica,6.3,3.3,virginica,6.0,2.5
101,virginica,5.8,2.7,virginica,5.1,1.9
102,virginica,7.1,3.0,virginica,5.9,2.1
103,virginica,6.3,2.9,virginica,5.6,1.8
104,virginica,6.5,3.0,virginica,5.8,2.2
105,virginica,7.6,3.0,virginica,6.6,2.1
106,virginica,4.9,2.5,virginica,4.5,1.7
107,virginica,7.3,2.9,virginica,6.3,1.8
108,virginica,6.7,2.5,virginica,5.8,1.8
109,virginica,7.2,3.6,virginica,6.1,2.5
110,virginica,6.5,3.2,virginica,5.1,2.0
111,virginica,6.4,2.7,virginica,5.3,1.9
112,virginica,6.8,3.0,virginica,5.5,2.1
113,virginica,5.7,2.5,virginica,5.0,2.0
114,virginica,5.8,2.8,virginica,5.1,2.4
115,virginica,6.4,3.2,virginica,5.3,2.3
116,virginica,6.5,3.0,virginica,5.5,1.8
117,virginica,7.7,3.8,virginica,6.7,2.2
118,virginica,7.7,2.6,virginica,6.9,2.3
119,virginica,6.0,2.2,virginica,5.0,1.5
120,virginica,6.9,3.2,virginica,5.7,2.3
121,virginica,5.6,2.8,virginica,4.9,2.0
122,virginica,7.7,2.8,virginica,6.7,2.0
123,virginica,6.3,2.7,virginica,4.9,1.8
124,virginica,6.7,3.3,virginica,5.7,2.1
125,virginica,7.2,3.2,virginica,6.0,1.8
126,virginica,6.2,2.8,virginica,4.8,1.8
127,virginica,6.1,3.0,virginica,4.9,1.8
128,virginica,6.4,2.8,virginica,5.6,2.1
129,virginica,7.2,3.0,virginica,5.8,1.6
130,virginica,7.4,2.8,virginica,6.1,1.9
131,virginica,7.9,3.8,virginica,6.4,2.0
132,virginica,6.4,2.8,virginica,5.6,2.2
133,virginica,6.3,2.8,virginica,5.1,1.5
134,virginica,6.1,2.6,virginica,5.6,1.4
135,virginica,7.7,3.0,virginica,6.1,2.3
136,virginica,6.3,3.4,virginica,5.6,2.4
137,virginica,6.4,3.1,virginica,5.5,1.8
138,virginica,6.0,3.0,virginica,4.8,1.8
139,virginica,6.9,3.1,virginica,5.4,2.1
140,virginica,6.7,3.1,virginica,5.6,2.4
141,virginica,6.9,3.1,virginica,5.1,2.3
142,virginica,5.8,2.7,virginica,5.1,1.9
143,virginica,6.8,3.2,virginica,5.9,2.3
144,virginica,6.7,3.3,virginica,5.7,2.5
145,virginica,6.7,3.0,virginica,5.2,2.3
146,virginica,6.3,2.5,virginica,5.0,1.9
147,virginica,6.5,3.0,virginica,5.2,2.0
148,virginica,6.2,3.4,virginica,5.4,2.3
149,virginica,5.9,3.0,virginica,5.1,1.8

In [181]:
reverse2 = pd.merge(sepal, petal, how="inner")
reverse2

        species  sepal_length  sepal_width  petal_length  petal_width
0        setosa           5.1          3.5           1.4          0.2
1        setosa           5.1          3.5           1.4          0.2
2        setosa           5.1          3.5           1.3          0.2
3        setosa           5.1          3.5           1.5          0.2
4        setosa           5.1          3.5           1.4          0.2
...         ...           ...          ...           ...          ...
7495  virginica           5.9          3.0           5.2          2.3
7496  virginica           5.9          3.0           5.0          1.9
7497  virginica           5.9          3.0           5.2          2.0
7498  virginica           5.9          3.0           5.4          2.3
7499  virginica           5.9          3.0           5.1          1.8

[7500 rows x 5 columns]